version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8123"
    container_name: nest-backend
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: job_nest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
