export enum APPLY_JOB_STATUS {
  PENDING = 'DANG_XU_LY',
  INTERVIEW = 'PHONG_VAN',
  ACCEPTED = 'NHAN',
  REJECTED = 'HUY',
}

export enum ROLE_LIST {
  ADMIN = 'QUAN_TRI',
  EMPLOYER = 'NHA_TUYEN_DUNG',
  CANDIDATE = 'UNG_VIEN',
}

export enum INTERVIEW_STATUS {
  PENDING = 'DANG_XU_LY',
  CONFIRMED = 'CHAP_NHAN',
  COMPLETED = 'HOAN_THANH',
  CANCELLED = 'HUY',
}
export enum PROVIDER_LIST {
  GOOGLE = 'GOOGLE',
  GITHUB = 'GITHUB',
}
